### ISSUE TITLE
Failure creating ElasticsearchDomain when deploying solution

### ISSUE THREAD

**Issue by 914005** [amazon-connect/amazon-connect-call-quality-monitoring#1]
I've run the Deploy for this solution twice and both times it has failed. In CloudFormation, this is the error reported:

Embedded stack arn:aws:cloudformation:us-east-1:{ACCOUNT_ID}:stack/ConnectMonitoringStack-ElasticsearchStackNestedStackElasticsearchStackNestedStackResou-9F9TUZ6NW2AG/04384f80-1d3a-11eb-83b7-12e26def3eab was not successfully created: The following resource(s) failed to create: [ElasticsearchProviderframeworkonEventServiceRoleDefaultPolicy5158B6DF, ElasticsearchDomain].

This is being run by a role with AdministratorAccess policy. I've confirmed I can create an elasticsearch domain via a different stack which runs fine. Thus, it seems it is not a permissions issue. Since this solution doesn't enable CloudWatch logs or make any other forensic data available, I don't know how to troubleshoot further. Any advise?

**Comment by kqia040** [comment]
Hey there, could you confirm if you are using the default in the CcpUrl parameter input in the format "https://<alias>.awsapps.com/connect/ccp-v2

**Comment by kqia040** [comment]
Hey there, resolving the issue for now. Please feel free to reopen if you are seeing this again.
