### ISSUE TITLE
Deploy worked but we don't see data in elastic-search

### ISSUE THREAD

**Issue by rrkraft** [amazon-connect/amazon-connect-call-quality-monitoring#10]
We deployed the application without issues. When we make a call we don't see data in ES. I don't even see hits to CloudFront or the API gateway. 
We see this error on the client computer:
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.
1 directive
Source Location    Directive    Status
2.8245e0e2.chunk.js:1    script-src    blocked

Any chance this is related or our problem?

Thanks

**Comment by kqia040** [comment]
hey @rrkraft are you using the cloudfront URL (custom CCP) that is deployed by the solution?

**Comment by rrkraft** [comment]
Yes, we do.

Rainer

**Comment by rrkraft** [comment]
We figured out this issue. We enforce a WAF in front of cloudfront so we had to add a custom name to get it through the WAF. We did not change connect to use the custom name. After we changed that I do see the calls coming into cloudfront and then the API GW. But now I get a 403 error on the API GW. The URL it hits is just /prod without a method. That doesn't look right to me. 
Any thoughts where to go next? How does it determine which method to call? 
I'm also starting to debug the javascript code now to see what's going on there. But any help is probably speeding up this process quite a bit.

**Comment by kqia040** [comment]
Hey @rrkraft do you have any auth enabled on the API Gateway? If you are using a custom domain name you might also need to modify the Lambda function, it uses proxy integration with API Gateway and there could potentially be a CORs related error

**Comment by dfw100** [comment]
@rrkraft could you please respond to @kqia040 questions above so that we can look in to it?
