### ISSUE TITLE
How to customize the ElasticSearch intances and use with a custom dialer

### ISSUE THREAD

**Issue by ierwind** [amazon-connect/amazon-connect-call-quality-monitoring#12]
Hi Team,

Im looking to deploy this with lesser ElasticSearch instances and use a custom dialer.
I know I can change the elasticsearch-stack.ts file to modify the instance that will be created, but once I have completed the modification, how am I be able to deploy this using sar?

Also, will this work with a custom dialer?

Thanks,
Erwin

**Comment by kqia040** [comment]
Hi Erwin, the SAR deployment mechanism uses the original CDK project. If you make modifications to the elasticsearch-stack.ts file, you will need to use `cdk deploy` to deploy the project locally. 

Could you clarify what your question is around integrating with a custom dialler?

**Comment by dfw100** [comment]
Hi @ierwind Could you please clarify your question regarding integrating with a custom dialler?

**Comment by ierwind** [comment]
Hey Team, thanks for coming back to me. I was pulled away from the project so I didn't able to see this through but i think the team went to what @kqia040 was suggesting. 
Thanks for your time in answering my question - be it vague.
Cheers!
