### ISSUE TITLE
Creation failed 

### ISSUE THREAD

**Issue by Kannan2022** [amazon-connect/amazon-connect-call-quality-monitoring#16]
<html>
<body>

CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [2f83d1e3-58e2-4eb5-803e-bfa7cb216805]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by dayyehm** [comment]
The failure in Codebuild shows similar error when running the debug : 
--
362 |  
363 |  
364 | [Container] 2021/09/25 14:10:14 Running command cdk deploy --require-approval never --debug --debug --verbose
365 | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
366 | !!                                                                                                           !!
367 | !!  Node v10.19.0 has reached end-of-life and will no longer be supported in new releases after 2021-09-01.  !!
368 | !!  Please upgrade to a supported node version as soon as possible.                                          !!
369 | !!                                                                                                           !!
370 | !!  As of the current release, supported versions of node are:                                               !!
371 | !!  - ^12.7.0                                                                                                !!
372 | !!  - ^14.5.0                                                                                                !!
373 | !!  - ^16.3.0                                                                                                !!
374 | !!                                                                                                           !!
375 | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
376 | CDK toolkit version: 1.124.0 (build 65761fe)
377 | Command line arguments: { _: [ 'deploy' ],
378 | 'require-approval': 'never',
379 | requireApproval: 'never',
380 | debug: true,
381 | verbose: 1,
382 | v: 1,
383 | lookups: true,
384 | 'ignore-errors': false,
385 | ignoreErrors: false,
386 | json: false,
387 | j: false,
388 | ec2creds: undefined,
389 | i: undefined,
390 | 'version-reporting': undefined,
391 | versionReporting: undefined,
392 | 'path-metadata': true,
393 | pathMetadata: true,
394 | 'asset-metadata': true,
395 | assetMetadata: true,
396 | 'role-arn': undefined,
397 | r: undefined,
398 | roleArn: undefined,
399 | staging: true,
400 | 'no-color': false,
401 | noColor: false,
402 | all: false,
403 | 'build-exclude': [],
404 | E: [],
405 | buildExclude: [],
406 | ci: false,
407 | execute: true,
408 | force: false,
409 | f: false,
410 | parameters: [ {} ],
411 | 'previous-parameters': true,
412 | previousParameters: true,
413 | '$0': '/usr/local/bin/cdk' }
414 | cdk.json: {
415 | "app": "npx ts-node bin/metricscdk.ts"
416 | }
417 | cdk.context.json: {
418 | "@aws-cdk/core:enableStackNameDuplicates": "true",
419 | "aws-cdk:enableDiffNoFail": "true"
420 | }
421 | merged settings: { versionReporting: true,
422 | pathMetadata: true,
423 | output: 'cdk.out',
424 | app: 'npx ts-node bin/metricscdk.ts',
425 | context: {},
426 | debug: true,
427 | assetMetadata: true,
428 | requireApproval: 'never',
429 | toolkitBucket: {},
430 | staging: true,
431 | bundlingStacks: [ '*' ],
432 | lookups: true }
433 | Toolkit stack: CDKToolkit
434 | Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
435 | Resolving default credentials
436 | Retrieved account ID 502706730710 from disk cache
437 | Setting "CDK_DEFAULT_ACCOUNT" environment variable to 502706730710
438 | context: { '@aws-cdk/core:enableStackNameDuplicates': 'true',
439 | 'aws-cdk:enableDiffNoFail': 'true',
440 | 'aws:cdk:enable-path-metadata': true,
441 | 'aws:cdk:enable-asset-metadata': true,
442 | 'aws:cdk:version-reporting': true,
443 | 'aws:cdk:bundling-stacks': [ '*' ] }
444 | outdir: cdk.out
445 | env: { CDK_DEFAULT_REGION: 'us-east-1',
446 | CDK_DEFAULT_ACCOUNT: '502706730710',
447 | CDK_DEBUG: 'true',
448 | CDK_CONTEXT_JSON:
449 | '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true,"aws:cdk:version-reporting":true,"aws:cdk:bundling-stacks":["*"]}',
450 | CDK_OUTDIR: 'cdk.out',
451 | CDK_CLI_ASM_VERSION: '14.0.0',
452 | CDK_CLI_VERSION: '1.124.0' }
453 | CCP URL must be the https:// url to your ccp-v2 softphone
454 | Subprocess exited with error 1
455 | Error: Subprocess exited with error 1
456 | at ChildProcess.proc.on.code (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)
457 | at ChildProcess.emit (events.js:198:13)
458 | at ChildProcess.EventEmitter.emit (domain.js:448:20)
459 | at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

**Comment by Kannan2022** [comment]
yes .. please suggest on this i  have 2 enterprise accounts tested in both the results are same.

**Comment by dayyehm** [comment]
Looking at this error seems like an issue that is reported here : 

https://github.com/aws/aws-cdk/issues/2004
https://www.gitmemory.com/issue/awslabs/aws-solutions-constructs/113/761014146


=============
455 | Error: Subprocess exited with error 1
456 | at ChildProcess.proc.on.code (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)
457 | at ChildProcess.emit (events.js:198:13)
458 | at ChildProcess.EventEmitter.emit (domain.js:448:20)
459 | at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
==============

I'm investigating this , will provide further details soon

**Comment by kqia040** [comment]
Hey team,

Could you try to deploy the CDK locally?

```
git clone git@github.com:amazon-connect/amazon-connect-call-quality-monitoring.git

npm install -g aws-cdk
npm install -g typescript
cdk --version
export ACCOUNT_ID=`aws sts get-caller-identity --query Account --output text`
export AWS_REGION=YOURREGION
cdk bootstrap aws://$ACCOUNT_ID/$AWS_REGION

export CCP_URL=YOURURL
cd Amazon-connect-monitoring/monitoring-stack-cdk
npm install
cdk deploy --require-approval never
```

**Comment by Kannan2022** [comment]
Preparing your terminal...
[cloudshell-user@ip-10-1-179-104 ~]$ git clone git@github.com:amazon-connect/amazon-connect-call-quality-monitoring.git
Cloning into 'amazon-connect-call-quality-monitoring'...
Permission denied (publickey).
fatal: Could not read from remote repository

**Comment by kqia040** [comment]
Try the other Github URL  to git clone

https://github.com/amazon-connect/amazon-connect-call-quality-monitoring.git

**Comment by dfw100** [comment]
@Kannan2022 did you get a chance to try the new Github URL?

**Comment by kqia040** [comment]
Closing issue, please feel free to reopen if you have other issues
