### ISSUE TITLE
Implementing CCP into custom dashboard solution

### ISSUE THREAD

**Issue by hannelorebervoets** [amazon-connect/amazon-connect-call-quality-monitoring#2]
I've been trying to implement the custom CCP (the Cloudfront URL) into our custom dashboard web application, without any succes so far. 
Using the standard Amazon Connect API  we have created a custom dashboard application which uses the standard CCP to call and answer calls (our dashboard has some features such as seeing what caller is waiting in line etc). When browsing to the web application, it will redirect to the CCP login page and after filling in your credentials, will log you in as an agent in the dashboard web application so you can call via the dashboard application. 
In the application code, we just fill in the CCP url to make it work. Whenever I replace the default CCP with the Cloudfront URL, the web application won't log you in. You can browse the application, it will redirect you to the CloudFront url CCP to try to log you in but after entering credentials you are not logged in and the dashboard page keeps refreshing and trying to log you in. 
I've tried to diagnose the issue by having a console open in Chrome and looking at the logs. When comparing logs between the standard CCP and the Cloudfront one, the Cloudfront will constanly say the following when refreshing:

> "connect-streams-min.d4ba3cfa.js:1 [2021-01-20T16:32:41.008Z] [WARN]: We can't be the master for topic 'connect::softphone' because there is no master client!"

However I have no clue what that means and how I can solve it. I've added a console log from when the CloudFront url was used. Any help would be much appreciated thanks! 
(the "Refused to display '' in a frame because it set 'X-Frame-Options' to 'sameorigin'" is also given when using the original CCP which does work) 
[log-cloudfront-url.log](https://github.com/amazon-connect/amazon-connect-call-quality-monitoring/files/5856060/log-cloudfront-url.log)

**Comment by kqia040** [comment]
Hi there, please let me know if I've misinterpreted any thing. 

From what I understand you are embedding the Cloudfront URL in your custom dashboard which already embeds the original CCP by replacing the CCP url in your original application code to the Cloudfront URL. If I am understanding this correct, unfortunately this will not work. 

The Cloudfront url created by the stack in this solution is essentially a custom CCP website, that embeds the original CCP and builds on top of the streams js and rtc js libraries. To achieve this in your customer dashboard/website, you will need look at how the Cloudfront page leverages the [connect-custom-implementation.js ](https://github.com/amazon-connect/amazon-connect-call-quality-monitoring/blob/master/monitoring-stack-cdk/resources/frontend/connect-custom-implementation.js) in the index.html page, along with the [dependencies, stream JS file and the RTC JS file. ](https://github.com/amazon-connect/amazon-connect-call-quality-monitoring/blob/master/monitoring-stack-cdk/resources/custom-resources/frontend-generator/index.html#L12)

**Comment by hannelorebervoets** [comment]
Hi! 

Thanks so much for your reply. This does answer my question. I found this GitHub through [this Amazon article ](https://aws.amazon.com/blogs/contact-center/easily-monitor-call-quality-with-amazon-connect/) but I think I might have misinterpreted it. I thought it was just a custom softphone that would be deployed and that would be able to be integrated like the default CCP softphone. 
I will be looking into your suggestions, thanks a lot!
