### ISSUE TITLE
Use relay state

### ISSUE THREAD

**Issue by issameddine** [amazon-connect/amazon-connect-call-quality-monitoring#5]
Hi

We deployed the package with the SAML URL. Our problem is that our Identity provider redirects us to AWS Console and not to Amazon connect.
Is it possible to add a Relaystate URL? 
Thanks

**Comment by anandadi** [comment]
https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html

**Comment by kqia040** [comment]
Hey there, unfortunately the relay state is set by the identity provider. As per the docs linked by @anandadi.

**Comment by kqia040** [comment]
Please reopen if you have any other questions
