### ISSUE TITLE
How to integrate with custom Cognito Pool

### ISSUE THREAD

**Issue by Swethamr402** [amazon-connect/amazon-connect-call-quality-monitoring#6]
Hi Team,

I need to configure with Custom Cognito where users already created in other pool and I need to map with another cloudfront URL /Route53 URL which is already in prod.

Can you please guide what steps I should follow.

Thanks,
Swetha

**Comment by kqia040** [comment]
Hey @Swethamr402 this would require modifying the cdk project to use your existing Custom Cognito pool. To confirm you are using this pool for the Elasticsearch/Kibana right?

**Comment by Swethamr402** [comment]
Yes I need use the custom pool for Elastic search/Kibana.
May I know which file to change , any guidence related to custom integration?

**Comment by kqia040** [comment]
@Swethamr402 You will need to customize the cdk project before you deploy. In this file around line 153-156 is where the Cognito options are configured for the ES cluster, you may need to remove the resources that exist by default in the project, and import the resources that you have in your account already.

https://github.com/amazon-connect/amazon-connect-call-quality-monitoring/blob/master/monitoring-stack-cdk/lib/elasticsearch-stack.ts#L153

**Comment by Swethamr402** [comment]
Thanks for the suggestion. I will look in to this.

Meanwhile I was trying to deploy in other region , I am facing permission issue.
Attached is the scrrenshot,

Can you please help me resolve 

![image](https://user-images.githubusercontent.com/9315915/113126252-13eaa980-9235-11eb-9458-c11db2068fac.png)

**Comment by taylor-zr** [comment]
Hello @Swethamr402

We've deployed a solution that resolves this issue. The AWSLambdaFullAccess policy was deprecated.

Please deploy and let us know if you have any issues.

**Comment by Swethamr402** [comment]
Any update on this please ?

**Comment by kqia040** [comment]
Hey @Swethamr402 could you try redeploying? Earlier this week we updated the artifact in the SAR's deployment mechanism.

**Comment by kqia040** [comment]
Hey @Swethamr402 how did it go? Were you able to deploy successfully?

**Comment by Swethamr402** [comment]
ya it successfully deployed,
Thanks.

**Comment by mcosicaws** [comment]
Thanks for the confirmation, much appreciated. I am resolving the issue, but please feel free to open a new one, should you need any additional help.
