### ISSUE TITLE
App deploy fails if account/region has not been bootstrapped with CDK previously

### ISSUE THREAD

**Issue by hanselds** [amazon-connect/amazon-connect-call-quality-monitoring#7]
Hello,

I have not worked with CDK before in my account/region and tried to deploy this app. The stack failed as `cdk bootstrap` executed from CodeBuild was not able to create the CDK staging bucket successfully.

 I have isolated this issue to the CodeBuild service role not having the necessary permissions to S3, specifically adding PublicAccessBlock settings. I manually added the permission to the role and the application deployed successfully. 

Thanks,
Hansel

**Comment by kqia040** [comment]
Thanks for submitting the MR. Changes merged.
