### ISSUE TITLE
New Amazon Connect URL change

### ISSUE THREAD

**Issue by msdyung** [amazon-connect/amazon-connect-call-quality-monitoring#9]
https://github.com/amazon-connect/amazon-connect-call-quality-monitoring/blob/00acf2a4c56ac81755aefd4c35cd893c32bcc058/monitoring-stack-cdk/lib/monitoring-stack.ts#L27

Hi, we found that any new Amazon Connect instance created will no longer come with domain name .awsapps.com
In other word, the line mentioned above will not pass and we failed to deploy using this stack. 

Would you please update this code? The new URL format for Amazon Connect is 
my.connect.aws

Thanks

**Comment by drumadrian** [comment]
I have the same issue: 

My domain has the format: 
https://mydomain.my.connect.aws/ccp-v2

**Comment by matwerber1** [comment]
Forked and trying to fix to submit a PR. Found another spot where a change will be needed: 

https://github.com/amazon-connect/amazon-connect-call-quality-monitoring/blob/223eeda25cb3fd6b7e0bc70184d33ea8e972fba8/monitoring-stack-cdk/lib/elasticsearch-stack.ts#L51
